### ISSUE TITLE
	Overlay manifest:package attribute declared at AndroidManifest.xml:2:5-48 value=(com.example.audio_recognition_app) 	has a different value=(com.example.audio_recognition_app) declared in main manifest at AndroidManifest.xml:2:5-54

### ISSUE THREAD

**Issue by aakashcode1708** [cmalbuquerque/audio_recognition_app#3]
Overlay manifest:package attribute declared at AndroidManifest.xml:2:5-48 value=(com.example.audio_recognition_app)
	has a different value=(com.example.audio_recognition_app) declared in main manifest at AndroidManifest.xml:2:5-54
	Suggestion: remove the overlay declaration at AndroidManifest.xml 	and place it in the build.gradle:
		flavorName {
			applicationId = "com.example.audio_recognition_app"
}

when i am running this project I am facing this problem

**Comment by cmalbuquerque** [comment]
@aakashcode1708 I am sorry for answering you late.
Did you downloaded this repository or created a new Flutter project and added the files? 
Did you try the suggestion returned in the output (remove the declaration showed and place it in the `build.gradle`)?

**Comment by aakashcode1708** [comment]
solved
